package com.example.nexuswallet.feature.wallet.ui


import androidx.compose.animation.*
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import com.example.nexuswallet.R
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.hilt.lifecycle.viewmodel.compose.hiltViewModel
import com.example.nexuswallet.feature.wallet.data.walletsrefactor.BitcoinNetwork
import com.example.nexuswallet.feature.wallet.data.walletsrefactor.EthereumNetwork
import com.example.nexuswallet.feature.wallet.data.walletsrefactor.NativeETH
import com.example.nexuswallet.feature.wallet.data.walletsrefactor.SPLToken
import com.example.nexuswallet.feature.wallet.data.walletsrefactor.SolanaCoin
import com.example.nexuswallet.feature.wallet.data.walletsrefactor.SolanaNetwork
import com.example.nexuswallet.feature.wallet.data.walletsrefactor.USDCToken
import com.example.nexuswallet.feature.wallet.data.walletsrefactor.USDTToken
import com.example.nexuswallet.feature.wallet.data.walletsrefactor.Wallet
import com.example.nexuswallet.ui.theme.bitcoinLight
import com.example.nexuswallet.ui.theme.ethereumLight
import com.example.nexuswallet.ui.theme.solanaLight
import com.example.nexuswallet.ui.theme.usdcLight

val usdtLight = Color(0xFF26A17B)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun WalletCreationScreen(
    onNavigateUp: () -> Unit,
    onNavigateToMain: () -> Unit,
    viewModel: WalletCreationViewModel = hiltViewModel()
) {
    val uiState by viewModel.uiState.collectAsState()
    val currentStep by viewModel.currentStep.collectAsState()
    val mnemonic by viewModel.mnemonic.collectAsState()
    val coinSelection by viewModel.coinSelection.collectAsState()
    val walletName by viewModel.walletName.collectAsState()
    val isMnemonicGenerated by viewModel.isMnemonicGenerated.collectAsState()
    val enteredWords by viewModel.enteredWords.collectAsState()

    // Track if user has seen the mnemonic warning
    var hasSeenSecurityWarning by remember { mutableStateOf(false) }

    // Handle navigation when wallet is created
    LaunchedEffect(uiState) {
        if (uiState is WalletCreationUiState.WalletCreated) {
            onNavigateToMain()
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        "Create Wallet",
                        color = MaterialTheme.colorScheme.onSurface
                    )
                },
                navigationIcon = {
                    if (currentStep > 0) {
                        IconButton(onClick = {
                            if (currentStep == 1 && !hasSeenSecurityWarning) {
                                onNavigateUp()
                            } else {
                                viewModel.previousStep()
                            }
                        }) {
                            Icon(
                                Icons.Default.ArrowBack,
                                "Back",
                                tint = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surface
                )
            )
        }
    ) { padding ->
        if (currentStep < 4 && uiState is WalletCreationUiState.Loading) {
            LoadingScreen()
            return@Scaffold
        }

        if (currentStep < 4 && uiState is WalletCreationUiState.Error) {
            ErrorScreen(
                message = (uiState as WalletCreationUiState.Error).message,
                onRetry = { viewModel.reset() }
            )
            return@Scaffold
        }

        WalletCreationStepper(
            currentStep = currentStep,
            padding = padding,
            content = {
                when (currentStep) {
                    0 -> CoinSelectionStep(
                        coinSelection = coinSelection,
                        onSelectionChange = { updatedSelection ->
                            viewModel.updateCoinSelection(
                                includeBitcoinMainnet = updatedSelection.includeBitcoinMainnet,
                                includeBitcoinTestnet = updatedSelection.includeBitcoinTestnet,
                                includeEthereumMainnet = updatedSelection.includeEthereumMainnet,
                                includeEthereumSepolia = updatedSelection.includeEthereumSepolia,
                                includeSolanaMainnet = updatedSelection.includeSolanaMainnet,
                                includeSolanaDevnet = updatedSelection.includeSolanaDevnet,
                                includeUSDCMainnet = updatedSelection.includeUSDCMainnet,
                                includeUSDCSepolia = updatedSelection.includeUSDCSepolia,
                                includeUSDTMainnet = updatedSelection.includeUSDTMainnet
                            )
                        },
                        onNext = { viewModel.nextStep() }
                    )

                    1 -> {
                        if (!hasSeenSecurityWarning) {
                            SecurityWarningDialog(
                                onAccept = {
                                    hasSeenSecurityWarning = true
                                    if (!isMnemonicGenerated) {
                                        viewModel.generateMnemonic()
                                    }
                                },
                                onCancel = { viewModel.previousStep() }
                            )
                        }

                        if (hasSeenSecurityWarning) {
                            if (mnemonic.isNotEmpty()) {
                                MnemonicDisplayStep(
                                    mnemonic = mnemonic,
                                    onNext = { viewModel.nextStep() },
                                    onBack = { viewModel.previousStep() }
                                )
                            } else {
                                Box(
                                    modifier = Modifier.fillMaxSize(),
                                    contentAlignment = Alignment.Center
                                ) {
                                    Column(
                                        horizontalAlignment = Alignment.CenterHorizontally
                                    ) {
                                        CircularProgressIndicator(
                                            color = MaterialTheme.colorScheme.primary
                                        )
                                        Spacer(modifier = Modifier.height(16.dp))
                                        Text(
                                            "Generating secure recovery phrase...",
                                            color = MaterialTheme.colorScheme.onSurfaceVariant
                                        )
                                    }
                                }
                            }
                        }
                    }

                    2 -> MnemonicVerificationStep(
                        mnemonic = mnemonic,
                        enteredWords = enteredWords,
                        onAddWord = { word -> viewModel.addWordToVerification(word) },
                        onRemoveWord = { index -> viewModel.removeWordFromVerification(index) },
                        onVerify = {
                            if (viewModel.completeVerificationAndMoveNext()) {
                                viewModel.nextStep()
                            }
                        },
                        onBack = { viewModel.previousStep() }
                    )

                    3 -> WalletNameStep(
                        walletName = walletName,
                        onNameChange = { viewModel.setWalletName(it) },
                        onCreate = { viewModel.createWallet() }
                    )

                    4 -> {
                        when (uiState) {
                            is WalletCreationUiState.WalletCreated -> {
                                val wallet = (uiState as WalletCreationUiState.WalletCreated).wallet
                                WalletSuccessStep(
                                    wallet = wallet,
                                    onFinish = onNavigateToMain
                                )
                            }
                            is WalletCreationUiState.Loading -> {
                                Box(
                                    modifier = Modifier.fillMaxSize(),
                                    contentAlignment = Alignment.Center
                                ) {
                                    Column(
                                        horizontalAlignment = Alignment.CenterHorizontally
                                    ) {
                                        CircularProgressIndicator(
                                            color = MaterialTheme.colorScheme.primary
                                        )
                                        Spacer(modifier = Modifier.height(16.dp))
                                        Text(
                                            "Creating wallet...",
                                            color = MaterialTheme.colorScheme.onSurfaceVariant
                                        )
                                    }
                                }
                            }
                            else -> {
                                LaunchedEffect(Unit) {
                                    viewModel.previousStep()
                                }
                                LoadingScreen()
                            }
                        }
                    }
                }
            }
        )
    }
}

@Composable
fun WalletCreationStepper(
    currentStep: Int,
    padding: PaddingValues,
    content: @Composable () -> Unit
) {
    val steps = listOf("Coins", "Backup", "Verify", "Name", "Complete")
    val stepDescriptions = remember(currentStep) {
        when (currentStep) {
            0 -> "Select which cryptocurrencies and networks to include"
            1 -> "Backup your recovery phrase"
            2 -> "Verify your backup"
            3 -> "Personalize your wallet"
            4 -> "Wallet created successfully"
            else -> ""
        }
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(padding)
            .background(MaterialTheme.colorScheme.background)
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp, vertical = 12.dp)
        ) {
            Text(
                text = "Step ${currentStep + 1} of ${steps.size}",
                style = MaterialTheme.typography.labelMedium,
                color = MaterialTheme.colorScheme.primary,
                fontWeight = FontWeight.Medium
            )

            Spacer(modifier = Modifier.height(4.dp))

            Text(
                text = stepDescriptions,
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }

        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 24.dp, vertical = 8.dp),
            horizontalArrangement = Arrangement.SpaceBetween
        ) {
            steps.forEachIndexed { index, step ->
                StepIndicator(
                    stepNumber = index + 1,
                    stepName = step,
                    isActive = index == currentStep,
                    isCompleted = index < currentStep,
                    isNext = index == currentStep + 1
                )
            }
        }

        LinearProgressIndicator(
            progress = { (currentStep + 1) / steps.size.toFloat() },
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp, vertical = 4.dp)
                .height(4.dp),
            color = MaterialTheme.colorScheme.primary,
            trackColor = MaterialTheme.colorScheme.surfaceVariant
        )

        Spacer(modifier = Modifier.height(24.dp))

        Box(
            modifier = Modifier
                .fillMaxSize()
                .padding(horizontal = 16.dp)
        ) {
            content()
        }
    }
}

@Composable
fun CoinSelectionStep(
    coinSelection: WalletCreationViewModel.CoinSelection,
    onSelectionChange: (WalletCreationViewModel.CoinSelection) -> Unit,
    onNext: () -> Unit
) {
    var localSelection by remember { mutableStateOf(coinSelection) }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
    ) {
        Text(
            text = "Select Assets & Networks",
            style = MaterialTheme.typography.headlineMedium,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.onSurface
        )

        Spacer(modifier = Modifier.height(8.dp))

        Text(
            text = "Choose which cryptocurrencies and networks to include",
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )

        Spacer(modifier = Modifier.height(24.dp))

        // ============ BITCOIN SECTION ============
        Text(
            text = "Bitcoin",
            style = MaterialTheme.typography.titleLarge,
            fontWeight = FontWeight.Bold,
            color = bitcoinLight,
            modifier = Modifier.padding(bottom = 8.dp)
        )

        // Bitcoin Mainnet
        NetworkToggleCard(
            iconRes = R.drawable.bitcoin,
            color = bitcoinLight,
            coinName = "Bitcoin Mainnet",
            coinSymbol = "BTC",
            networkName = "Mainnet",
            isSelected = localSelection.includeBitcoinMainnet,
            onSelectedChange = {
                localSelection = localSelection.copy(includeBitcoinMainnet = it)
                onSelectionChange(localSelection)
            }
        )

        Spacer(modifier = Modifier.height(8.dp))

        // Bitcoin Testnet
        NetworkToggleCard(
            iconRes = R.drawable.bitcoin,
            color = bitcoinLight.copy(alpha = 0.7f),
            coinName = "Bitcoin Testnet",
            coinSymbol = "BTC",
            networkName = "Testnet",
            isSelected = localSelection.includeBitcoinTestnet,
            onSelectedChange = {
                localSelection = localSelection.copy(includeBitcoinTestnet = it)
                onSelectionChange(localSelection)
            }
        )

        Spacer(modifier = Modifier.height(24.dp))

        // ============ ETHEREUM SECTION ============
        Text(
            text = "Ethereum",
            style = MaterialTheme.typography.titleLarge,
            fontWeight = FontWeight.Bold,
            color = ethereumLight,
            modifier = Modifier.padding(bottom = 8.dp)
        )

        // Ethereum Mainnet
        NetworkToggleCard(
            iconRes = R.drawable.ethereum,
            color = ethereumLight,
            coinName = "Ethereum Mainnet",
            coinSymbol = "ETH",
            networkName = "Mainnet",
            isSelected = localSelection.includeEthereumMainnet,
            onSelectedChange = {
                localSelection = localSelection.copy(includeEthereumMainnet = it)
                onSelectionChange(localSelection)
            }
        )

        Spacer(modifier = Modifier.height(8.dp))

        // Ethereum Sepolia
        NetworkToggleCard(
            iconRes = R.drawable.ethereum,
            color = ethereumLight.copy(alpha = 0.7f),
            coinName = "Ethereum Sepolia",
            coinSymbol = "ETH",
            networkName = "Sepolia (Testnet)",
            isSelected = localSelection.includeEthereumSepolia,
            onSelectedChange = {
                localSelection = localSelection.copy(includeEthereumSepolia = it)
                onSelectionChange(localSelection)
            }
        )

        Spacer(modifier = Modifier.height(24.dp))

        // ============ SOLANA SECTION ============
        Text(
            text = "Solana",
            style = MaterialTheme.typography.titleLarge,
            fontWeight = FontWeight.Bold,
            color = solanaLight,
            modifier = Modifier.padding(bottom = 8.dp)
        )

        // Solana Mainnet
        NetworkToggleCard(
            iconRes = R.drawable.solana,
            color = solanaLight,
            coinName = "Solana Mainnet",
            coinSymbol = "SOL",
            networkName = "Mainnet",
            isSelected = localSelection.includeSolanaMainnet,
            onSelectedChange = {
                localSelection = localSelection.copy(includeSolanaMainnet = it)
                onSelectionChange(localSelection)
            }
        )

        Spacer(modifier = Modifier.height(8.dp))

        // Solana Devnet
        NetworkToggleCard(
            iconRes = R.drawable.solana,
            color = solanaLight.copy(alpha = 0.7f),
            coinName = "Solana Devnet",
            coinSymbol = "SOL",
            networkName = "Devnet (Testnet)",
            isSelected = localSelection.includeSolanaDevnet,
            onSelectedChange = {
                localSelection = localSelection.copy(includeSolanaDevnet = it)
                onSelectionChange(localSelection)
            }
        )

        Spacer(modifier = Modifier.height(24.dp))

        // ============ TOKENS SECTION ============
        Text(
            text = "Tokens",
            style = MaterialTheme.typography.titleLarge,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.primary,
            modifier = Modifier.padding(bottom = 8.dp)
        )

        // USDC Mainnet
        NetworkToggleCard(
            iconRes = R.drawable.usdc,
            color = usdcLight,
            coinName = "USDC",
            coinSymbol = "USDC",
            networkName = "Ethereum Mainnet",
            isSelected = localSelection.includeUSDCMainnet,
            onSelectedChange = {
                localSelection = localSelection.copy(includeUSDCMainnet = it)
                onSelectionChange(localSelection)
            }
        )

        Spacer(modifier = Modifier.height(8.dp))

        // USDC Sepolia
        NetworkToggleCard(
            iconRes = R.drawable.usdc,
            color = usdcLight.copy(alpha = 0.7f),
            coinName = "USDC",
            coinSymbol = "USDC",
            networkName = "Ethereum Sepolia",
            isSelected = localSelection.includeUSDCSepolia,
            onSelectedChange = {
                localSelection = localSelection.copy(includeUSDCSepolia = it)
                onSelectionChange(localSelection)
            }
        )

        Spacer(modifier = Modifier.height(8.dp))

        // USDT Mainnet
        NetworkToggleCard(
            iconRes = R.drawable.usdc,
            color = usdtLight,
            coinName = "USDT",
            coinSymbol = "USDT",
            networkName = "Ethereum Mainnet",
            isSelected = localSelection.includeUSDTMainnet,
            onSelectedChange = {
                localSelection = localSelection.copy(includeUSDTMainnet = it)
                onSelectionChange(localSelection)
            }
        )

        Spacer(modifier = Modifier.weight(1f))
        Spacer(modifier = Modifier.height(16.dp))

        // Summary Card
        Card(
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(12.dp),
            colors = CardDefaults.cardColors(
                containerColor = MaterialTheme.colorScheme.surfaceVariant
            )
        ) {
            Column(
                modifier = Modifier.padding(16.dp)
            ) {
                Text(
                    text = "Selected Assets",
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.onSurface
                )

                Spacer(modifier = Modifier.height(8.dp))

                val selectedCount = listOf(
                    localSelection.includeBitcoinMainnet to "Bitcoin Mainnet",
                    localSelection.includeBitcoinTestnet to "Bitcoin Testnet",
                    localSelection.includeEthereumMainnet to "Ethereum Mainnet",
                    localSelection.includeEthereumSepolia to "Ethereum Sepolia",
                    localSelection.includeSolanaMainnet to "Solana Mainnet",
                    localSelection.includeSolanaDevnet to "Solana Devnet",
                    localSelection.includeUSDCMainnet to "USDC Mainnet",
                    localSelection.includeUSDCSepolia to "USDC Sepolia",
                    localSelection.includeUSDTMainnet to "USDT Mainnet"
                ).filter { it.first }.map { it.second }

                if (selectedCount.isEmpty()) {
                    Text(
                        text = "No assets selected",
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        style = MaterialTheme.typography.bodyMedium
                    )
                } else {
                    selectedCount.forEach { asset ->
                        Text(
                            text = "• $asset",
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            style = MaterialTheme.typography.bodySmall,
                            modifier = Modifier.padding(vertical = 2.dp)
                        )
                    }
                }
            }
        }

        Spacer(modifier = Modifier.height(16.dp))

        Button(
            onClick = onNext,
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(12.dp),
            enabled = localSelection.includeBitcoinMainnet ||
                    localSelection.includeBitcoinTestnet ||
                    localSelection.includeEthereumMainnet ||
                    localSelection.includeEthereumSepolia ||
                    localSelection.includeSolanaMainnet ||
                    localSelection.includeSolanaDevnet ||
                    localSelection.includeUSDCMainnet ||
                    localSelection.includeUSDCSepolia ||
                    localSelection.includeUSDTMainnet,
            colors = ButtonDefaults.buttonColors(
                containerColor = MaterialTheme.colorScheme.primary,
                contentColor = MaterialTheme.colorScheme.onPrimary
            )
        ) {
            Text("Continue")
        }

        Spacer(modifier = Modifier.height(16.dp))
    }
}

@Composable
fun NetworkToggleCard(
    iconRes: Int,
    color: Color,
    coinName: String,
    coinSymbol: String,
    networkName: String,
    isSelected: Boolean,
    onSelectedChange: (Boolean) -> Unit
) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(
            containerColor = if (isSelected) color.copy(alpha = 0.05f)
            else MaterialTheme.colorScheme.surface
        ),
        border = if (isSelected) BorderStroke(1.dp, color) else BorderStroke(1.dp, MaterialTheme.colorScheme.outline.copy(alpha = 0.3f)),
        elevation = CardDefaults.cardElevation(defaultElevation = 0.dp)
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp)
                .clickable { onSelectedChange(!isSelected) },
            verticalAlignment = Alignment.CenterVertically
        ) {
            // Icon with no background
            Box(
                modifier = Modifier.size(48.dp),
                contentAlignment = Alignment.Center
            ) {
                Icon(
                    painter = painterResource(id = iconRes),
                    contentDescription = coinName,
                    tint = Color.Unspecified,
                    modifier = Modifier.size(36.dp)
                )
            }

            Spacer(modifier = Modifier.width(16.dp))

            Column(
                modifier = Modifier.weight(1f)
            ) {
                Text(
                    text = coinName,
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold,
                    color = if (isSelected) color else MaterialTheme.colorScheme.onSurface
                )
                Text(
                    text = "$coinSymbol • $networkName",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }

            Checkbox(
                checked = isSelected,
                onCheckedChange = onSelectedChange,
                colors = CheckboxDefaults.colors(
                    checkedColor = color,
                    uncheckedColor = MaterialTheme.colorScheme.onSurfaceVariant
                )
            )
        }
    }
}

@Composable
fun StepIndicator(
    stepNumber: Int,
    stepName: String,
    isActive: Boolean,
    isCompleted: Boolean,
    isNext: Boolean = false
) {
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = Modifier.width(50.dp)
    ) {
        Box(
            modifier = Modifier
                .size(36.dp)
                .clip(CircleShape)
                .background(
                    color = when {
                        isCompleted -> MaterialTheme.colorScheme.primary
                        isActive -> MaterialTheme.colorScheme.primaryContainer
                        isNext -> MaterialTheme.colorScheme.primary.copy(alpha = 0.1f)
                        else -> MaterialTheme.colorScheme.surfaceVariant
                    }
                )
                .border(
                    width = if (isActive) 2.dp else 0.dp,
                    color = MaterialTheme.colorScheme.primary,
                    shape = CircleShape
                ),
            contentAlignment = Alignment.Center
        ) {
            if (isCompleted) {
                Icon(
                    imageVector = Icons.Default.Check,
                    contentDescription = "Completed",
                    tint = MaterialTheme.colorScheme.onPrimary,
                    modifier = Modifier.size(18.dp)
                )
            } else {
                Text(
                    text = stepNumber.toString(),
                    color = when {
                        isActive -> MaterialTheme.colorScheme.onPrimaryContainer
                        isNext -> MaterialTheme.colorScheme.primary
                        else -> MaterialTheme.colorScheme.onSurfaceVariant
                    },
                    fontWeight = FontWeight.Bold
                )
            }
        }

        Spacer(modifier = Modifier.height(8.dp))

        Text(
            text = stepName,
            style = MaterialTheme.typography.labelSmall,
            color = when {
                isActive || isCompleted -> MaterialTheme.colorScheme.primary
                isNext -> MaterialTheme.colorScheme.primary.copy(alpha = 0.8f)
                else -> MaterialTheme.colorScheme.onSurfaceVariant
            },
            fontWeight = if (isActive) FontWeight.Bold else FontWeight.Normal,
            maxLines = 1,
            overflow = TextOverflow.Ellipsis
        )
    }
}

@Composable
fun CoinToggleCard(
    icon: ImageVector,
    color: Color,
    coinName: String,
    coinSymbol: String,
    isSelected: Boolean,
    onSelectedChange: (Boolean) -> Unit
) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(
            containerColor = if (isSelected) color.copy(alpha = 0.1f)
            else MaterialTheme.colorScheme.surfaceVariant
        ),
        border = if (isSelected) BorderStroke(2.dp, color) else null
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp)
                .clickable { onSelectedChange(!isSelected) },
            verticalAlignment = Alignment.CenterVertically
        ) {
            Box(
                modifier = Modifier
                    .size(48.dp)
                    .clip(CircleShape)
                    .background(color),
                contentAlignment = Alignment.Center
            ) {
                Icon(
                    imageVector = icon,
                    contentDescription = coinName,
                    tint = Color.White,
                    modifier = Modifier.size(24.dp)
                )
            }

            Spacer(modifier = Modifier.width(16.dp))

            Column(
                modifier = Modifier.weight(1f)
            ) {
                Text(
                    text = coinName,
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.onSurface
                )
                Text(
                    text = coinSymbol,
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }

            Checkbox(
                checked = isSelected,
                onCheckedChange = onSelectedChange,
                colors = CheckboxDefaults.colors(
                    checkedColor = color
                )
            )
        }
    }
}

@Composable
fun NetworkChip(
    name: String,
    isSelected: Boolean,
    onClick: () -> Unit
) {
    Card(
        modifier = Modifier
            .clickable { onClick() },
        shape = RoundedCornerShape(8.dp),
        colors = CardDefaults.cardColors(
            containerColor = if (isSelected)
                MaterialTheme.colorScheme.primary
            else
                MaterialTheme.colorScheme.surfaceVariant
        )
    ) {
        Text(
            text = name,
            modifier = Modifier
                .fillMaxWidth()
                .padding(vertical = 12.dp),
            textAlign = TextAlign.Center,
            color = if (isSelected)
                MaterialTheme.colorScheme.onPrimary
            else
                MaterialTheme.colorScheme.onSurfaceVariant,
            style = MaterialTheme.typography.bodyMedium
        )
    }
}

@Composable
fun SecurityWarningDialog(
    onAccept: () -> Unit,
    onCancel: () -> Unit
) {
    AlertDialog(
        onDismissRequest = onCancel,
        containerColor = MaterialTheme.colorScheme.surface,
        title = {
            Text(
                text = "⚠️ Security Warning",
                color = MaterialTheme.colorScheme.error,
                style = MaterialTheme.typography.titleMedium
            )
        },
        text = {
            Text(
                text = "Your recovery phrase is the ONLY way to restore your wallet. " +
                        "If you lose it, you lose access to your funds permanently. " +
                        "Never share it with anyone!",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        },
        confirmButton = {
            TextButton(
                onClick = onAccept,
                colors = ButtonDefaults.textButtonColors(
                    contentColor = MaterialTheme.colorScheme.primary
                )
            ) {
                Text("I Understand")
            }
        },
        dismissButton = {
            TextButton(
                onClick = onCancel,
                colors = ButtonDefaults.textButtonColors(
                    contentColor = MaterialTheme.colorScheme.onSurfaceVariant
                )
            ) {
                Text("Cancel")
            }
        }
    )
}

@Composable
fun MnemonicDisplayStep(
    mnemonic: List<String>,
    onNext: () -> Unit,
    onBack: () -> Unit
) {
    var hasWrittenDown by remember { mutableStateOf(false) }
    var hasStoredSafely by remember { mutableStateOf(false) }

    LazyColumn(
        modifier = Modifier.fillMaxSize(),
        contentPadding = PaddingValues(bottom = 100.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        // Header
        item {
            Column(
                modifier = Modifier.padding(horizontal = 16.dp)
            ) {
                Text(
                    text = "🔐 Your Recovery Phrase",
                    style = MaterialTheme.typography.headlineSmall,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.onSurface
                )

                Spacer(modifier = Modifier.height(8.dp))

                // Critical warning
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(
                        containerColor = MaterialTheme.colorScheme.errorContainer
                    ),
                    elevation = CardDefaults.cardElevation(defaultElevation = 4.dp)
                ) {
                    Column(
                        modifier = Modifier.padding(16.dp)
                    ) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Icon(
                                imageVector = Icons.Default.Warning,
                                contentDescription = "Warning",
                                tint = MaterialTheme.colorScheme.onErrorContainer
                            )
                            Spacer(modifier = Modifier.width(8.dp))
                            Text(
                                text = "Critical Security Step",
                                style = MaterialTheme.typography.titleMedium,
                                color = MaterialTheme.colorScheme.onErrorContainer,
                                fontWeight = FontWeight.Bold
                            )
                        }

                        Spacer(modifier = Modifier.height(8.dp))

                        Text(
                            text = "Write down these 12 words IN ORDER on paper. " +
                                    "Never store digitally. This is the ONLY way to restore your wallet.",
                            color = MaterialTheme.colorScheme.onErrorContainer,
                            style = MaterialTheme.typography.bodyMedium
                        )
                    }
                }
            }
        }

        // Mnemonic Grid
        item {
            LazyVerticalGrid(
                columns = GridCells.Fixed(3),
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 16.dp)
                    .heightIn(min = 300.dp, max = 400.dp),
                horizontalArrangement = Arrangement.spacedBy(12.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                items(mnemonic) { word ->
                    MnemonicDisplayChip(
                        word = word,
                        index = mnemonic.indexOf(word) + 1
                    )
                }
            }
        }

        // Safety Tips
        item {
            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 16.dp),
                colors = CardDefaults.cardColors(
                    containerColor = MaterialTheme.colorScheme.surfaceVariant
                )
            ) {
                Column(
                    modifier = Modifier.padding(16.dp)
                ) {
                    Text(
                        text = "📝 Safety Checklist:",
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.onSurface
                    )

                    Spacer(modifier = Modifier.height(12.dp))

                    SafetyChecklistItem(
                        text = "✓ Write on paper (not digital)",
                        checked = true
                    )
                    SafetyChecklistItem(
                        text = "✓ Store in secure location",
                        checked = true
                    )
                    SafetyChecklistItem(
                        text = "✓ Never share with anyone",
                        checked = true
                    )
                    SafetyChecklistItem(
                        text = "✓ Keep away from moisture/fire",
                        checked = true
                    )
                }
            }
        }

        // Confirmation checkboxes
        item {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 16.dp)
            ) {
                Row(
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Checkbox(
                        checked = hasWrittenDown,
                        onCheckedChange = { hasWrittenDown = it },
                        colors = CheckboxDefaults.colors(
                            checkedColor = MaterialTheme.colorScheme.primary
                        )
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(
                        text = "I have written down all 12 words on paper",
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                }

                Spacer(modifier = Modifier.height(8.dp))

                Row(
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Checkbox(
                        checked = hasStoredSafely,
                        onCheckedChange = { hasStoredSafely = it },
                        colors = CheckboxDefaults.colors(
                            checkedColor = MaterialTheme.colorScheme.primary
                        )
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(
                        text = "I have stored them in a secure location",
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                }
            }
        }

        // Spacer to separate from buttons
        item {
            Spacer(modifier = Modifier.height(20.dp))
        }
    }

    // Fixed buttons at bottom
    Box(
        modifier = Modifier.fillMaxSize(),
        contentAlignment = Alignment.BottomCenter
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .background(
                    Brush.verticalGradient(
                        colors = listOf(
                            Color.Transparent,
                            MaterialTheme.colorScheme.surface.copy(alpha = 0.9f),
                            MaterialTheme.colorScheme.surface
                        ),
                        startY = 0f,
                        endY = 100f
                    )
                )
                .padding(16.dp)
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                OutlinedButton(
                    onClick = onBack,
                    modifier = Modifier.weight(1f),
                    shape = RoundedCornerShape(12.dp),
                    colors = ButtonDefaults.outlinedButtonColors(
                        contentColor = MaterialTheme.colorScheme.primary
                    )
                ) {
                    Text("Back")
                }

                Button(
                    onClick = onNext,
                    modifier = Modifier.weight(1f),
                    shape = RoundedCornerShape(12.dp),
                    enabled = hasWrittenDown && hasStoredSafely,
                    colors = ButtonDefaults.buttonColors(
                        containerColor = MaterialTheme.colorScheme.primary,
                        contentColor = MaterialTheme.colorScheme.onPrimary
                    )
                ) {
                    Text("I've Backed It Up")
                }
            }
        }
    }
}

@Composable
fun MnemonicDisplayChip(
    word: String,
    index: Int
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .aspectRatio(1.2f),
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.primaryContainer,
            contentColor = MaterialTheme.colorScheme.onPrimaryContainer
        ),
        elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
    ) {
        Box(
            modifier = Modifier.fillMaxSize(),
            contentAlignment = Alignment.Center
        ) {
            Column(
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text(
                    text = "$index.",
                    style = MaterialTheme.typography.labelSmall,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.onPrimaryContainer.copy(alpha = 0.7f)
                )
                Spacer(modifier = Modifier.height(8.dp))
                Text(
                    text = word,
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.onPrimaryContainer
                )
            }
        }
    }
}

@Composable
fun SafetyChecklistItem(text: String, checked: Boolean) {
    Row(
        verticalAlignment = Alignment.CenterVertically,
        modifier = Modifier.padding(vertical = 4.dp)
    ) {
        Icon(
            imageVector = if (checked) Icons.Default.CheckCircle else Icons.Default.Circle,
            contentDescription = null,
            tint = if (checked) MaterialTheme.colorScheme.primary
            else MaterialTheme.colorScheme.onSurfaceVariant,
            modifier = Modifier.size(20.dp)
        )
        Spacer(modifier = Modifier.width(8.dp))
        Text(
            text = text,
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurface
        )
    }
}

@Composable
fun MnemonicVerificationStep(
    mnemonic: List<String>,
    enteredWords: List<String>,
    onAddWord: (String) -> Unit,
    onRemoveWord: (Int) -> Unit,
    onVerify: () -> Unit,
    onBack: () -> Unit
) {
    val shuffledWords = remember { mnemonic.shuffled() }
    var verificationError by remember { mutableStateOf(false) }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(horizontal = 16.dp)
            .verticalScroll(rememberScrollState())
            .background(MaterialTheme.colorScheme.background)
    ) {
        // Back button
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            TextButton(
                onClick = onBack,
                colors = ButtonDefaults.textButtonColors(
                    contentColor = MaterialTheme.colorScheme.primary
                )
            ) {
                Icon(Icons.Default.ArrowBack, contentDescription = "Back")
                Spacer(modifier = Modifier.width(4.dp))
                Text("Back")
            }

            Text(
                text = "Step 2/3",
                style = MaterialTheme.typography.labelSmall,
                color = MaterialTheme.colorScheme.primary
            )
        }

        Spacer(modifier = Modifier.height(16.dp))

        // Title
        Text(
            text = "Verify Recovery Phrase",
            style = MaterialTheme.typography.headlineSmall,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.onSurface
        )

        Spacer(modifier = Modifier.height(8.dp))

        Text(
            text = "Tap words in the correct order",
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )

        Spacer(modifier = Modifier.height(24.dp))

        // Selected words
        Card(
            colors = CardDefaults.cardColors(
                containerColor = MaterialTheme.colorScheme.surfaceVariant
            ),
            shape = RoundedCornerShape(12.dp)
        ) {
            Column(
                modifier = Modifier.padding(16.dp)
            ) {
                Text(
                    text = "Selected Words (${enteredWords.size}/${mnemonic.size})",
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )

                Spacer(modifier = Modifier.height(12.dp))

                if (enteredWords.isEmpty()) {
                    Text(
                        text = "No words selected yet",
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.5f),
                        textAlign = TextAlign.Center,
                        modifier = Modifier.fillMaxWidth()
                    )
                } else {
                    // Vertical FlowRow for selected words
                    FlowRow(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                        verticalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        enteredWords.forEachIndexed { index, word ->
                            SimpleSelectedChip(
                                word = word,
                                index = index + 1,
                                onRemove = { onRemoveWord(index) }
                            )
                        }
                    }
                }
            }
        }

        Spacer(modifier = Modifier.height(24.dp))

        // Available words
        Text(
            text = "Tap to select:",
            style = MaterialTheme.typography.labelLarge,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )

        Spacer(modifier = Modifier.height(12.dp))

        // Manual 4-column grid
        Column(
            modifier = Modifier.fillMaxWidth()
        ) {
            for (row in 0 until 3) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    for (col in 0 until 4) {
                        val index = row * 4 + col
                        if (index < shuffledWords.size) {
                            val word = shuffledWords[index]
                            Box(modifier = Modifier.weight(1f)) {
                                if (!enteredWords.contains(word)) {
                                    SimpleWordChip(
                                        word = word,
                                        onClick = { onAddWord(word) }
                                    )
                                } else {
                                    Spacer(modifier = Modifier.height(44.dp))
                                }
                            }
                        }
                    }
                }
                Spacer(modifier = Modifier.height(8.dp))
            }
        }

        Spacer(modifier = Modifier.height(32.dp))

        // Error message
        if (verificationError) {
            Card(
                colors = CardDefaults.cardColors(
                    containerColor = MaterialTheme.colorScheme.errorContainer
                ),
                shape = RoundedCornerShape(8.dp)
            ) {
                Row(
                    modifier = Modifier.padding(12.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Icon(
                        imageVector = Icons.Default.Error,
                        contentDescription = "Error",
                        tint = MaterialTheme.colorScheme.onErrorContainer,
                        modifier = Modifier.size(18.dp)
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(
                        text = "Wrong order. Please try again.",
                        color = MaterialTheme.colorScheme.onErrorContainer,
                        style = MaterialTheme.typography.bodyMedium
                    )
                }
            }
            Spacer(modifier = Modifier.height(16.dp))
        }

        Button(
            onClick = {
                if (enteredWords.size == mnemonic.size && enteredWords == mnemonic) {
                    verificationError = false
                    onVerify()
                } else {
                    verificationError = true
                }
            },
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(12.dp),
            enabled = enteredWords.size == mnemonic.size,
            colors = ButtonDefaults.buttonColors(
                containerColor = MaterialTheme.colorScheme.primary,
                contentColor = MaterialTheme.colorScheme.onPrimary
            )
        ) {
            Text("Verify & Continue")
        }

        Spacer(modifier = Modifier.height(32.dp))
    }
}

@Composable
fun SimpleSelectedChip(
    word: String,
    index: Int,
    onRemove: () -> Unit
) {
    Card(
        onClick = onRemove,
        shape = RoundedCornerShape(8.dp),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.primaryContainer,
            contentColor = MaterialTheme.colorScheme.onPrimaryContainer
        )
    ) {
        Row(
            modifier = Modifier.padding(horizontal = 12.dp, vertical = 8.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Text(
                text = "$index.",
                style = MaterialTheme.typography.labelSmall,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.onPrimaryContainer
            )
            Spacer(modifier = Modifier.width(4.dp))
            Text(
                text = word,
                style = MaterialTheme.typography.bodyMedium,
                fontWeight = FontWeight.Medium,
                maxLines = 1,
                overflow = TextOverflow.Ellipsis,
                color = MaterialTheme.colorScheme.onPrimaryContainer
            )
            Spacer(modifier = Modifier.width(4.dp))
            Icon(
                imageVector = Icons.Default.Close,
                contentDescription = "Remove",
                modifier = Modifier.size(14.dp),
                tint = MaterialTheme.colorScheme.onPrimaryContainer
            )
        }
    }
}

@Composable
fun SimpleWordChip(
    word: String,
    onClick: () -> Unit
) {
    Card(
        onClick = onClick,
        shape = RoundedCornerShape(8.dp),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.surfaceVariant
        ),
        border = BorderStroke(1.dp, MaterialTheme.colorScheme.outline.copy(alpha = 0.2f))
    ) {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .height(44.dp),
            contentAlignment = Alignment.Center
        ) {
            Text(
                text = word,
                style = MaterialTheme.typography.bodyMedium,
                fontWeight = FontWeight.Medium,
                maxLines = 1,
                overflow = TextOverflow.Ellipsis,
                color = MaterialTheme.colorScheme.onSurface
            )
        }
    }
}

@Composable
fun WalletNameStep(
    walletName: String,
    onNameChange: (String) -> Unit,
    onCreate: () -> Unit
) {
    Column(
        modifier = Modifier.fillMaxSize()
    ) {
        Text(
            text = "Name Your Wallet",
            style = MaterialTheme.typography.headlineSmall,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.onSurface
        )

        Spacer(modifier = Modifier.height(8.dp))

        Text(
            text = "Give your wallet a name for easy identification",
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )

        Spacer(modifier = Modifier.height(24.dp))

        OutlinedTextField(
            value = walletName,
            onValueChange = onNameChange,
            modifier = Modifier.fillMaxWidth(),
            label = {
                Text(
                    "Wallet Name",
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            },
            placeholder = {
                Text(
                    "e.g., My Savings Wallet",
                    color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.5f)
                )
            },
            singleLine = true,
            shape = RoundedCornerShape(12.dp),
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = MaterialTheme.colorScheme.primary,
                unfocusedBorderColor = MaterialTheme.colorScheme.outline,
                cursorColor = MaterialTheme.colorScheme.primary,
                focusedLabelColor = MaterialTheme.colorScheme.primary,
                unfocusedLabelColor = MaterialTheme.colorScheme.onSurfaceVariant
            )
        )

        Spacer(modifier = Modifier.height(8.dp))

        Text(
            text = "Tip: Use a descriptive name like 'Savings' or 'Trading'",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )

        Spacer(modifier = Modifier.weight(1f))

        Button(
            onClick = onCreate,
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(12.dp),
            enabled = walletName.isNotBlank(),
            colors = ButtonDefaults.buttonColors(
                containerColor = MaterialTheme.colorScheme.primary,
                contentColor = MaterialTheme.colorScheme.onPrimary
            )
        ) {
            Text("Create Wallet")
        }
    }
}

@Composable
fun WalletSuccessStep(
    wallet: Wallet,
    onFinish: () -> Unit
) {
    // Calculate total assets correctly
    val totalAssets = wallet.bitcoinCoins.size +
            wallet.solanaCoins.size +
            wallet.evmTokens.size +
            wallet.solanaCoins.flatMap { it.splTokens }.size

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(MaterialTheme.colorScheme.background)
            .verticalScroll(rememberScrollState()),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        // Success icon
        Box(
            modifier = Modifier
                .size(100.dp)
                .clip(RoundedCornerShape(50.dp))
                .background(MaterialTheme.colorScheme.primaryContainer),
            contentAlignment = Alignment.Center
        ) {
            Icon(
                imageVector = Icons.Default.CheckCircle,
                contentDescription = "Success",
                modifier = Modifier.size(48.dp),
                tint = MaterialTheme.colorScheme.primary
            )
        }

        Spacer(modifier = Modifier.height(32.dp))

        Text(
            text = "Wallet Created Successfully!",
            style = MaterialTheme.typography.headlineMedium,
            fontWeight = FontWeight.Bold,
            textAlign = TextAlign.Center,
            color = MaterialTheme.colorScheme.onSurface
        )

        Spacer(modifier = Modifier.height(8.dp))

        Card(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 24.dp),
            shape = RoundedCornerShape(16.dp),
            colors = CardDefaults.cardColors(
                containerColor = MaterialTheme.colorScheme.surfaceVariant
            )
        ) {
            Column(
                modifier = Modifier.padding(16.dp)
            ) {
                Text(
                    text = "Wallet Details",
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.onSurface
                )

                Spacer(modifier = Modifier.height(12.dp))

                Row(
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        "Name: ",
                        fontWeight = FontWeight.Medium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    Text(
                        wallet.name,
                        color = MaterialTheme.colorScheme.onSurface,
                        fontWeight = FontWeight.Bold
                    )
                }

                Spacer(modifier = Modifier.height(12.dp))

                Text(
                    "Enabled Assets:",
                    fontWeight = FontWeight.Medium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )

                Spacer(modifier = Modifier.height(8.dp))

                // Bitcoin Coins with icons
                wallet.bitcoinCoins.forEach { coin ->
                    val networkSuffix = if (coin.network != BitcoinNetwork.Mainnet) " (Testnet)" else ""
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        modifier = Modifier.padding(vertical = 4.dp)
                    ) {
                        Icon(
                            painter = painterResource(id = R.drawable.bitcoin),
                            contentDescription = "Bitcoin",
                            modifier = Modifier.size(20.dp),
                            tint = Color.Unspecified
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            text = "Bitcoin$networkSuffix",
                            color = bitcoinLight,
                            fontWeight = FontWeight.Medium
                        )
                    }
                }

                // Solana Coins with icons
                wallet.solanaCoins.forEach { coin ->
                    val networkSuffix = if (coin.network != SolanaNetwork.Mainnet) " (Devnet)" else ""
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        modifier = Modifier.padding(vertical = 4.dp)
                    ) {
                        Icon(
                            painter = painterResource(id = R.drawable.solana),
                            contentDescription = "Solana",
                            modifier = Modifier.size(20.dp),
                            tint = Color.Unspecified
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            text = "Solana$networkSuffix",
                            color = solanaLight,
                            fontWeight = FontWeight.Medium
                        )
                    }

                    // Show SPL tokens if any
                    if (coin.splTokens.isNotEmpty()) {
                        coin.splTokens.take(3).forEach { token ->
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                modifier = Modifier.padding(start = 28.dp, top = 2.dp, bottom = 2.dp) // FIXED: Individual padding
                            ) {
                                Box(
                                    modifier = Modifier
                                        .size(16.dp)
                                        .clip(CircleShape)
                                        .background(MaterialTheme.colorScheme.primary.copy(alpha = 0.1f)),
                                    contentAlignment = Alignment.Center
                                ) {
                                    Icon(
                                        imageVector = Icons.Outlined.Token,
                                        contentDescription = token.symbol,
                                        modifier = Modifier.size(10.dp),
                                        tint = MaterialTheme.colorScheme.primary
                                    )
                                }
                                Spacer(modifier = Modifier.width(6.dp))
                                Text(
                                    text = "${token.symbol} (SPL)",
                                    color = MaterialTheme.colorScheme.primary,
                                    style = MaterialTheme.typography.bodySmall
                                )
                            }
                        }
                        if (coin.splTokens.size > 3) {
                            Text(
                                text = "  • +${coin.splTokens.size - 3} more",
                                modifier = Modifier.padding(start = 28.dp),
                                color = MaterialTheme.colorScheme.onSurfaceVariant,
                                style = MaterialTheme.typography.bodySmall
                            )
                        }
                    }
                }

                // EVM Tokens with icons
                wallet.evmTokens.forEach { token ->
                    val (color, iconRes) = when (token) {
                        is NativeETH -> Pair(ethereumLight, R.drawable.ethereum)
                        is USDCToken -> Pair(usdcLight, R.drawable.usdc)
                        is USDTToken -> Pair(usdtLight, R.drawable.usdc)
                        else -> Pair(MaterialTheme.colorScheme.primary, null)
                    }

                    val networkSuffix = if (token.network != EthereumNetwork.Mainnet) " (Sepolia)" else ""

                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        modifier = Modifier.padding(vertical = 4.dp)
                    ) {
                        if (iconRes != null) {
                            Icon(
                                painter = painterResource(id = iconRes),
                                contentDescription = token.symbol,
                                modifier = Modifier.size(20.dp),
                                tint = Color.Unspecified
                            )
                        } else {
                            Box(
                                modifier = Modifier
                                    .size(20.dp)
                                    .clip(CircleShape)
                                    .background(color.copy(alpha = 0.1f)),
                                contentAlignment = Alignment.Center
                            ) {
                                Icon(
                                    imageVector = Icons.Outlined.Token,
                                    contentDescription = token.symbol,
                                    modifier = Modifier.size(12.dp),
                                    tint = color
                                )
                            }
                        }
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            text = "${token.symbol}$networkSuffix",
                            color = color,
                            fontWeight = FontWeight.Medium
                        )
                    }
                }

                // Primary Address (first available)
                val primaryAddress = wallet.evmTokens.firstOrNull()?.address
                    ?: wallet.bitcoinCoins.firstOrNull()?.address
                    ?: wallet.solanaCoins.firstOrNull()?.address

                if (primaryAddress != null) {
                    Spacer(modifier = Modifier.height(12.dp))
                    Divider(color = MaterialTheme.colorScheme.outline.copy(alpha = 0.3f))
                    Spacer(modifier = Modifier.height(8.dp))

                    Row(
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            imageVector = Icons.Outlined.AccountBalanceWallet,
                            contentDescription = "Address",
                            modifier = Modifier.size(16.dp),
                            tint = MaterialTheme.colorScheme.primary
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            "Primary Address: ",
                            fontWeight = FontWeight.Medium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                    Text(
                        text = primaryAddress,
                        style = MaterialTheme.typography.bodySmall,
                        fontFamily = FontFamily.Monospace,
                        color = MaterialTheme.colorScheme.onSurface,
                        modifier = Modifier.padding(start = 24.dp)
                    )
                }

                Spacer(modifier = Modifier.height(16.dp))
                Divider(color = MaterialTheme.colorScheme.outline.copy(alpha = 0.3f))
                Spacer(modifier = Modifier.height(8.dp))

                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.SpaceBetween,
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            imageVector = Icons.Outlined.AccountBalanceWallet,
                            contentDescription = "Total Assets",
                            modifier = Modifier.size(18.dp),
                            tint = MaterialTheme.colorScheme.primary
                        )
                        Spacer(modifier = Modifier.width(6.dp))
                        Text(
                            text = "Total Assets:",
                            style = MaterialTheme.typography.bodyMedium,
                            fontWeight = FontWeight.Medium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                    Text(
                        text = "$totalAssets",
                        style = MaterialTheme.typography.bodyLarge,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.primary
                    )
                }
            }
        }

        Spacer(modifier = Modifier.height(32.dp))

        Button(
            onClick = onFinish,
            modifier = Modifier
                .fillMaxWidth(0.8f)
                .padding(bottom = 32.dp),
            shape = RoundedCornerShape(12.dp),
            colors = ButtonDefaults.buttonColors(
                containerColor = MaterialTheme.colorScheme.primary,
                contentColor = MaterialTheme.colorScheme.onPrimary
            )
        ) {
            Icon(
                imageVector = Icons.Outlined.Dashboard,
                contentDescription = null,
                modifier = Modifier.size(18.dp)
            )
            Spacer(modifier = Modifier.width(8.dp))
            Text("Go to Dashboard")
        }
    }
}