package com.example.nexuswallet.feature.wallet.ui.walletcreation

import androidx.biometric.BiometricPrompt
import com.example.nexuswallet.feature.core.ui.isBiometricUserCancel
import com.example.nexuswallet.feature.core.ui.rememberBiometricPrompt
import androidx.compose.animation.animateColorAsState
import androidx.compose.animation.animateContentSize
import androidx.compose.animation.togetherWith
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Error
import androidx.compose.material.icons.filled.Warning
import androidx.compose.material.icons.outlined.Dashboard
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.hapticfeedback.HapticFeedbackType
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalHapticFeedback
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.ContextCompat
import androidx.hilt.lifecycle.viewmodel.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.example.nexuswallet.R
import com.example.nexuswallet.feature.core.ui.NexusTextField
import com.example.nexuswallet.feature.ethereum.domain.model.EVMTokenType
import com.example.nexuswallet.feature.wallet.domain.model.BitcoinNetwork
import com.example.nexuswallet.feature.wallet.domain.model.EthereumNetwork
import com.example.nexuswallet.feature.wallet.domain.model.NativeETH
import com.example.nexuswallet.feature.wallet.domain.model.Network
import com.example.nexuswallet.feature.wallet.domain.model.SolanaNetwork
import com.example.nexuswallet.feature.wallet.domain.model.USDCToken
import com.example.nexuswallet.feature.wallet.domain.model.USDTToken
import com.example.nexuswallet.feature.wallet.domain.model.Wallet
import com.example.nexuswallet.feature.wallet.ui.common.*
import com.example.nexuswallet.ui.theme.bitcoinLight
import com.example.nexuswallet.ui.theme.ethereumLight
import com.example.nexuswallet.ui.theme.solanaLight
import com.example.nexuswallet.ui.theme.usdcLight
import com.example.nexuswallet.ui.theme.usdtLight

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun WalletCreationScreen(
    onNavigateUp: () -> Unit,
    onNavigateToMain: () -> Unit,
    viewModel: WalletCreationViewModel = hiltViewModel()
) {
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
    val currentStep by viewModel.currentStep.collectAsStateWithLifecycle()
    val mnemonic by viewModel.mnemonic.collectAsStateWithLifecycle()
    val selectedNetworks by viewModel.selectedNetworks.collectAsStateWithLifecycle()
    val selectedTokens by viewModel.selectedTokens.collectAsStateWithLifecycle()
    val walletName by viewModel.walletName.collectAsStateWithLifecycle()
    val isMnemonicGenerated by viewModel.isMnemonicGenerated.collectAsStateWithLifecycle()
    val enteredWords by viewModel.enteredWords.collectAsStateWithLifecycle()
    val authRequest by viewModel.authRequest.collectAsStateWithLifecycle()
    val cryptoObject by viewModel.cryptoObject.collectAsStateWithLifecycle()

    val biometricPrompt = rememberBiometricPrompt(
        onSuccess = { result ->
            viewModel.onBiometricSuccess(result.cryptoObject?.cipher)
        },
        onError = { errorCode, errString ->
            if (!isBiometricUserCancel(errorCode)) {
                viewModel.setErrorMessage(errString.toString())
            }
        }
    )

    val biometricTitle = stringResource(R.string.biometric_authentication)
    val biometricSubtitle = stringResource(R.string.secure_your_wallet)
    val biometricCancel = stringResource(R.string.cancel)

    val promptInfo = remember(biometricTitle, biometricSubtitle, biometricCancel) {
        BiometricPrompt.PromptInfo.Builder()
            .setTitle(biometricTitle)
            .setSubtitle(biometricSubtitle)
            .setNegativeButtonText(biometricCancel)
            .build()
    }

    LaunchedEffect(authRequest) {
        if (authRequest != null) {
            if (cryptoObject != null) {
                biometricPrompt?.authenticate(promptInfo, BiometricPrompt.CryptoObject(cryptoObject!!))
            } else {
                biometricPrompt?.authenticate(promptInfo)
            }
        }
    }

    var hasSeenSecurityWarning by remember { mutableStateOf(false) }

    LaunchedEffect(uiState) {
        if (uiState is WalletCreationUiState.WalletCreated) {
            onNavigateToMain()
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        text = stringResource(R.string.create_wallet),
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.SemiBold,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                },
                navigationIcon = {
                    if (currentStep > 0) {
                        IconButton(
                            onClick = {
                                if (currentStep == 1 && !hasSeenSecurityWarning) {
                                    onNavigateUp()
                                } else {
                                    viewModel.previousStep()
                                }
                            }
                        ) {
                            Icon(
                                Icons.AutoMirrored.Filled.ArrowBack,
                                stringResource(R.string.back),
                                tint = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    } else {
                        IconButton(onClick = onNavigateUp) {
                            Icon(
                                Icons.AutoMirrored.Filled.ArrowBack,
                                stringResource(R.string.back),
                                tint = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surface
                )
            )
        }
    ) { padding ->
        if (currentStep < 4 && (uiState is WalletCreationUiState.Loading || uiState is WalletCreationUiState.WalletCreated)) {
            FullScreenLoading(message = stringResource(R.string.creating_wallet))
            return@Scaffold
        }

        if (currentStep < 4 && uiState is WalletCreationUiState.Error) {
            ErrorScreen(
                message = (uiState as WalletCreationUiState.Error).message,
                onRetry = { viewModel.reset() }
            )
            return@Scaffold
        }

        val steps = listOf(
            stringResource(R.string.step_networks),
            stringResource(R.string.step_backup),
            stringResource(R.string.step_verify),
            stringResource(R.string.step_name),
            stringResource(R.string.step_complete)
        )

        WalletCreationStepper(
            steps = steps,
            currentStep = currentStep,
            padding = padding,
            content = {
                when (currentStep) {
                    0 -> NetworkSelectionStep(
                        selectedNetworks = selectedNetworks,
                        selectedTokens = selectedTokens,
                        onNetworkToggle = { network, isSelected ->
                            viewModel.toggleNetwork(network, isSelected)
                        },
                        onTokenToggle = { network, tokenClass, isSelected ->
                            viewModel.toggleToken(network, tokenClass, isSelected)
                        },
                        onNext = { viewModel.nextStep() },
                        hasSelections = viewModel.hasSelections()
                    )

                    1 -> {
                        if (!hasSeenSecurityWarning) {
                            SecurityWarningDialog(
                                onAccept = {
                                    hasSeenSecurityWarning = true
                                    if (!isMnemonicGenerated) {
                                        viewModel.generateMnemonic()
                                    }
                                },
                                onCancel = { viewModel.previousStep() }
                            )
                        }

                        if (hasSeenSecurityWarning) {
                            if (mnemonic.isNotEmpty()) {
                                MnemonicDisplayStep(
                                    mnemonic = mnemonic.map { String(it) },
                                    onNext = { viewModel.nextStep() },
                                    onBack = { viewModel.previousStep() }
                                )
                            } else {
                                FullScreenLoading(message = stringResource(R.string.generating_recovery_phrase))
                            }
                        }
                    }

                    2 -> MnemonicVerificationStep(
                        mnemonic = mnemonic.map { String(it) },
                        enteredWords = enteredWords.map { String(it) },
                        onAddWord = { word -> viewModel.addWordToVerification(word.toCharArray()) },
                        onRemoveWord = { index -> viewModel.removeWordFromVerification(index) },
                        onVerify = {
                            if (viewModel.completeVerificationAndMoveNext()) {
                                viewModel.nextStep()
                            }
                        },
                        onBack = { viewModel.previousStep() }
                    )

                    3 -> WalletNameStep(
                        walletName = walletName,
                        onNameChange = { name -> viewModel.setWalletName(name) },
                        onCreate = { viewModel.createWallet() }
                    )

                    4 -> {
                        when (uiState) {
                            is WalletCreationUiState.WalletCreated -> {
                                val wallet = (uiState as WalletCreationUiState.WalletCreated).wallet
                                WalletSuccessStep(
                                    wallet = wallet,
                                    onFinish = onNavigateToMain
                                )
                            }

                            is WalletCreationUiState.Loading -> {
                                FullScreenLoading(message = stringResource(R.string.creating_wallet))
                            }

                            else -> {
                                LaunchedEffect(Unit) {
                                    viewModel.previousStep()
                                }
                                FullScreenLoading(message = stringResource(R.string.loading))
                            }
                        }
                    }
                }
            }
        )
    }
}

@Composable
fun WalletCreationStepper(
    steps: List<String>,
    currentStep: Int,
    padding: PaddingValues,
    content: @Composable () -> Unit
) {
    val stepDescriptions = when (currentStep) {
        0 -> stringResource(R.string.step_networks_desc)
        1 -> stringResource(R.string.step_backup_desc)
        2 -> stringResource(R.string.step_verify_desc)
        3 -> stringResource(R.string.step_name_desc)
        4 -> stringResource(R.string.step_complete_desc)
        else -> ""
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(padding)
            .background(MaterialTheme.colorScheme.background)
    ) {
        Surface(
            modifier = Modifier.fillMaxWidth(),
            color = MaterialTheme.colorScheme.surface,
            tonalElevation = 2.dp,
            shadowElevation = 2.dp
        ) {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 20.dp, vertical = 16.dp)
            ) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    Column {
                        Text(
                            text = steps[currentStep.coerceIn(steps.indices)],
                            style = MaterialTheme.typography.titleLarge,
                            fontWeight = FontWeight.Bold,
                            color = MaterialTheme.colorScheme.onSurface
                        )
                        Text(
                            text = stringResource(R.string.step_x_of_y, currentStep + 1, steps.size),
                            style = MaterialTheme.typography.labelMedium,
                            color = MaterialTheme.colorScheme.primary,
                            fontWeight = FontWeight.SemiBold
                        )
                    }

                    Box(contentAlignment = Alignment.Center) {
                        CircularProgressIndicator(
                            progress = { (currentStep + 1) / steps.size.toFloat() },
                            modifier = Modifier.size(48.dp),
                            strokeWidth = 4.dp,
                            color = MaterialTheme.colorScheme.primary,
                            trackColor = MaterialTheme.colorScheme.surfaceVariant,
                            strokeCap = androidx.compose.ui.graphics.StrokeCap.Round
                        )
                        Text(
                            text = "${((currentStep + 1) * 100 / steps.size)}%",
                            style = MaterialTheme.typography.labelSmall,
                            fontWeight = FontWeight.Bold,
                            color = MaterialTheme.colorScheme.onSurface
                        )
                    }
                }

                Spacer(modifier = Modifier.height(12.dp))

                Text(
                    text = stepDescriptions,
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    lineHeight = 20.sp
                )

                Spacer(modifier = Modifier.height(16.dp))

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    steps.indices.forEach { index ->
                        Box(
                            modifier = Modifier
                                .weight(1f)
                                .height(6.dp)
                                .clip(RoundedCornerShape(3.dp))
                                .background(
                                    when {
                                        index == currentStep -> MaterialTheme.colorScheme.primary
                                        index < currentStep -> MaterialTheme.colorScheme.primary.copy(alpha = 0.5f)
                                        else -> MaterialTheme.colorScheme.surfaceVariant
                                    }
                                )
                        )
                    }
                }
            }
        }

        Box(
            modifier = Modifier
                .fillMaxSize()
        ) {
            content()
        }
    }
}

@Composable
fun NetworkSelectionStep(
    selectedNetworks: Set<Network>,
    selectedTokens: Map<EthereumNetwork, Set<EVMTokenType>>,
    onNetworkToggle: (Network, Boolean) -> Unit,
    onTokenToggle: (EthereumNetwork, EVMTokenType, Boolean) -> Unit,
    onNext: () -> Unit,
    hasSelections: Boolean
) {
    val haptic = LocalHapticFeedback.current

    Column(
        modifier = Modifier
            .fillMaxSize()
    ) {
        LazyColumn(
            modifier = Modifier.weight(1f),
            contentPadding = PaddingValues(start = 16.dp, end = 16.dp, top = 16.dp, bottom = 24.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            item {
                SectionHeader(
                    title = stringResource(R.string.bitcoin),
                    color = bitcoinLight
                )
            }

            item {
                NetworkToggleCard(
                    iconRes = R.drawable.bitcoin,
                    color = bitcoinLight,
                    network = BitcoinNetwork.Mainnet,
                    coinName = stringResource(R.string.bitcoin_name),
                    coinSymbol = stringResource(R.string.bitcoin_symbol),
                    isSelected = selectedNetworks.contains(BitcoinNetwork.Mainnet),
                    onSelectedChange = { onNetworkToggle(BitcoinNetwork.Mainnet, it) }
                )
            }

            item {
                NetworkToggleCard(
                    iconRes = R.drawable.bitcoin,
                    color = bitcoinLight.copy(alpha = 0.7f),
                    network = BitcoinNetwork.Testnet,
                    coinName = stringResource(R.string.bitcoin_name),
                    coinSymbol = stringResource(R.string.bitcoin_symbol),
                    isSelected = selectedNetworks.contains(BitcoinNetwork.Testnet),
                    onSelectedChange = { onNetworkToggle(BitcoinNetwork.Testnet, it) }
                )
            }

            item {
                Spacer(modifier = Modifier.height(12.dp))
                SectionHeader(
                    title = stringResource(R.string.ethereum),
                    color = ethereumLight
                )
            }

            item {
                NetworkToggleCard(
                    iconRes = R.drawable.ethereum,
                    color = ethereumLight,
                    network = EthereumNetwork.Mainnet,
                    coinName = stringResource(R.string.ethereum_name),
                    coinSymbol = stringResource(R.string.ethereum_symbol),
                    isSelected = selectedNetworks.contains(EthereumNetwork.Mainnet),
                    onSelectedChange = { onNetworkToggle(EthereumNetwork.Mainnet, it) }
                )
            }

            item {
                NetworkToggleCard(
                    iconRes = R.drawable.ethereum,
                    color = ethereumLight.copy(alpha = 0.7f),
                    network = EthereumNetwork.Sepolia,
                    coinName = stringResource(R.string.ethereum_name),
                    coinSymbol = stringResource(R.string.ethereum_symbol),
                    isSelected = selectedNetworks.contains(EthereumNetwork.Sepolia),
                    onSelectedChange = { onNetworkToggle(EthereumNetwork.Sepolia, it) }
                )
            }

            item {
                Spacer(modifier = Modifier.height(12.dp))
                SectionHeader(
                    title = stringResource(R.string.solana),
                    color = solanaLight
                )
            }

            item {
                NetworkToggleCard(
                    iconRes = R.drawable.solana,
                    color = solanaLight,
                    network = SolanaNetwork.Mainnet,
                    coinName = stringResource(R.string.solana_name),
                    coinSymbol = stringResource(R.string.solana_symbol),
                    isSelected = selectedNetworks.contains(SolanaNetwork.Mainnet),
                    onSelectedChange = { onNetworkToggle(SolanaNetwork.Mainnet, it) }
                )
            }

            item {
                NetworkToggleCard(
                    iconRes = R.drawable.solana,
                    color = solanaLight.copy(alpha = 0.7f),
                    network = SolanaNetwork.Devnet,
                    coinName = stringResource(R.string.solana_name),
                    coinSymbol = stringResource(R.string.solana_symbol),
                    isSelected = selectedNetworks.contains(SolanaNetwork.Devnet),
                    onSelectedChange = { onNetworkToggle(SolanaNetwork.Devnet, it) }
                )
            }

            if (selectedNetworks.any { it is EthereumNetwork }) {
                item {
                    Spacer(modifier = Modifier.height(12.dp))
                    SectionHeader(
                        title = stringResource(R.string.tokens),
                        color = MaterialTheme.colorScheme.primary
                    )
                }

                item {
                    TokenToggleCard(
                        iconRes = R.drawable.usdc,
                        color = usdcLight,
                        network = EthereumNetwork.Mainnet,
                        evmTokenType = EVMTokenType.USDC,
                        tokenName = stringResource(R.string.usdc_name),
                        tokenSymbol = stringResource(R.string.usdc_symbol),
                        isSelected = selectedTokens[EthereumNetwork.Mainnet]?.contains(EVMTokenType.USDC) == true,
                        networkEnabled = selectedNetworks.contains(EthereumNetwork.Mainnet),
                        onSelectedChange = { onTokenToggle(EthereumNetwork.Mainnet, EVMTokenType.USDC, it) }
                    )
                }

                item {
                    TokenToggleCard(
                        iconRes = R.drawable.usdc,
                        color = usdcLight.copy(alpha = 0.7f),
                        network = EthereumNetwork.Sepolia,
                        evmTokenType = EVMTokenType.USDC,
                        tokenName = stringResource(R.string.usdc_name),
                        tokenSymbol = stringResource(R.string.usdc_symbol),
                        isSelected = selectedTokens[EthereumNetwork.Sepolia]?.contains(EVMTokenType.USDC) == true,
                        networkEnabled = selectedNetworks.contains(EthereumNetwork.Sepolia),
                        onSelectedChange = { onTokenToggle(EthereumNetwork.Sepolia, EVMTokenType.USDC, it) }
                    )
                }

                item {
                    TokenToggleCard(
                        iconRes = R.drawable.tether,
                        color = usdtLight,
                        network = EthereumNetwork.Mainnet,
                        evmTokenType = EVMTokenType.USDT,
                        tokenName = stringResource(R.string.usdt_name),
                        tokenSymbol = stringResource(R.string.usdt_symbol),
                        isSelected = selectedTokens[EthereumNetwork.Mainnet]?.contains(EVMTokenType.USDT) == true,
                        networkEnabled = selectedNetworks.contains(EthereumNetwork.Mainnet),
                        onSelectedChange = { onTokenToggle(EthereumNetwork.Mainnet, EVMTokenType.USDT, it) }
                    )
                }

                item {
                    TokenToggleCard(
                        iconRes = R.drawable.tether,
                        color = usdtLight.copy(alpha = 0.7f),
                        network = EthereumNetwork.Sepolia,
                        evmTokenType = EVMTokenType.USDT,
                        tokenName = stringResource(R.string.usdt_name),
                        tokenSymbol = stringResource(R.string.usdt_symbol),
                        isSelected = selectedTokens[EthereumNetwork.Sepolia]?.contains(EVMTokenType.USDT) == true,
                        networkEnabled = selectedNetworks.contains(EthereumNetwork.Sepolia),
                        onSelectedChange = { onTokenToggle(EthereumNetwork.Sepolia, EVMTokenType.USDT, it) }
                    )
                }
            }

            item {
                Spacer(modifier = Modifier.height(16.dp))
                AssetSummaryCard(
                    hasSelections = hasSelections,
                    selectedNetworks = selectedNetworks,
                    selectedTokens = selectedTokens
                )
            }
        }

        Surface(
            modifier = Modifier.fillMaxWidth(),
            tonalElevation = 8.dp,
            shadowElevation = 8.dp
        ) {
            Button(
                onClick = {
                    haptic.performHapticFeedback(HapticFeedbackType.LongPress)
                    onNext()
                },
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp)
                    .height(56.dp),
                shape = RoundedCornerShape(16.dp),
                enabled = hasSelections,
                colors = ButtonDefaults.buttonColors(
                    containerColor = MaterialTheme.colorScheme.primary,
                    contentColor = MaterialTheme.colorScheme.onPrimary
                )
            ) {
                Text(
                    text = stringResource(R.string.continue_button),
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold
                )
            }
        }
    }
}

@Composable
fun MnemonicDisplayStep(
    mnemonic: List<String>,
    onNext: () -> Unit,
    onBack: () -> Unit
) {
    val haptic = LocalHapticFeedback.current
    var hasWrittenDown by remember { mutableStateOf(false) }
    var hasStoredSafely by remember { mutableStateOf(false) }

    Column(modifier = Modifier.fillMaxSize()) {
        LazyColumn(
            modifier = Modifier.weight(1f),
            contentPadding = PaddingValues(start = 16.dp, end = 16.dp, top = 16.dp, bottom = 24.dp),
            verticalArrangement = Arrangement.spacedBy(20.dp)
        ) {
            item {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(
                        containerColor = MaterialTheme.colorScheme.errorContainer.copy(alpha = 0.7f)
                    ),
                    shape = RoundedCornerShape(16.dp),
                    border = BorderStroke(1.dp, MaterialTheme.colorScheme.error.copy(alpha = 0.2f))
                ) {
                    Row(
                        modifier = Modifier.padding(16.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            imageVector = Icons.Default.Warning,
                            contentDescription = null,
                            tint = MaterialTheme.colorScheme.error,
                            modifier = Modifier.size(24.dp)
                        )
                        Spacer(modifier = Modifier.width(12.dp))
                        Column {
                            Text(
                                text = stringResource(R.string.critical_security_step),
                                style = MaterialTheme.typography.titleSmall,
                                color = MaterialTheme.colorScheme.onErrorContainer,
                                fontWeight = FontWeight.Bold
                            )
                            Text(
                                text = stringResource(R.string.mnemonic_warning_desc),
                                color = MaterialTheme.colorScheme.onErrorContainer,
                                style = MaterialTheme.typography.bodySmall
                            )
                        }
                    }
                }
            }

            item {
                Surface(
                    modifier = Modifier.fillMaxWidth(),
                    color = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f),
                    shape = RoundedCornerShape(24.dp),
                    border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant)
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        val chunks = mnemonic.chunked(3)
                        chunks.forEach { chunk ->
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.spacedBy(8.dp)
                            ) {
                                chunk.forEach { word ->
                                    MnemonicDisplayChip(
                                        word = word,
                                        index = mnemonic.indexOf(word) + 1,
                                        modifier = Modifier.weight(1f)
                                    )
                                }
                                repeat(3 - chunk.size) {
                                    Spacer(modifier = Modifier.weight(1f))
                                }
                            }
                            Spacer(modifier = Modifier.height(8.dp))
                        }
                    }
                }
            }

            item {
                Text(
                    text = stringResource(R.string.safety_checklist_title),
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.onSurface,
                    modifier = Modifier.padding(horizontal = 4.dp)
                )

                Spacer(modifier = Modifier.height(8.dp))

                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .clip(RoundedCornerShape(16.dp))
                        .background(MaterialTheme.colorScheme.surface)
                        .padding(8.dp)
                ) {
                    SafetyConfirmationItem(
                        text = stringResource(R.string.written_down_confirmation),
                        checked = hasWrittenDown,
                        onCheckedChange = { hasWrittenDown = it }
                    )
                    Spacer(modifier = Modifier.height(4.dp))
                    SafetyConfirmationItem(
                        text = stringResource(R.string.stored_safely_confirmation),
                        checked = hasStoredSafely,
                        onCheckedChange = { hasStoredSafely = it }
                    )
                }
            }
        }

        Surface(
            modifier = Modifier.fillMaxWidth(),
            tonalElevation = 8.dp,
            shadowElevation = 8.dp
        ) {
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                OutlinedButton(
                    onClick = onBack,
                    modifier = Modifier
                        .weight(1f)
                        .height(56.dp),
                    shape = RoundedCornerShape(16.dp),
                    border = BorderStroke(1.dp, MaterialTheme.colorScheme.outline)
                ) {
                    Text(stringResource(R.string.back))
                }

                Button(
                    onClick = {
                        haptic.performHapticFeedback(HapticFeedbackType.LongPress)
                        onNext()
                    },
                    modifier = Modifier
                        .weight(1f)
                        .height(56.dp),
                    shape = RoundedCornerShape(16.dp),
                    enabled = hasWrittenDown && hasStoredSafely
                ) {
                    Text(
                        text = stringResource(R.string.backed_it_up),
                        fontWeight = FontWeight.Bold
                    )
                }
            }
        }
    }
}

@Composable
fun MnemonicVerificationStep(
    mnemonic: List<String>,
    enteredWords: List<String>,
    onAddWord: (String) -> Unit,
    onRemoveWord: (Int) -> Unit,
    onVerify: () -> Unit,
    onBack: () -> Unit
) {
    val shuffledWords = remember { mnemonic.shuffled() }
    var verificationError by remember { mutableStateOf(false) }
    val haptic = LocalHapticFeedback.current

    val borderColor by animateColorAsState(
        targetValue = if (verificationError) MaterialTheme.colorScheme.error 
                     else MaterialTheme.colorScheme.outlineVariant,
        label = "verification_border"
    )

    Column(modifier = Modifier.fillMaxSize()) {
        LazyColumn(
            modifier = Modifier.weight(1f),
            contentPadding = PaddingValues(start = 16.dp, end = 16.dp, top = 16.dp, bottom = 24.dp),
            verticalArrangement = Arrangement.spacedBy(24.dp)
        ) {
            item {
                Text(
                    text = stringResource(R.string.mnemonic_verification_title),
                    style = MaterialTheme.typography.bodyLarge,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    lineHeight = 24.sp
                )
            }

            item {
                Column(modifier = Modifier.animateContentSize()) {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(48.dp),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text(
                            text = stringResource(R.string.selected_words, enteredWords.size, mnemonic.size),
                            style = MaterialTheme.typography.titleSmall,
                            color = MaterialTheme.colorScheme.primary,
                            fontWeight = FontWeight.ExtraBold,
                            modifier = Modifier.padding(start = 4.dp)
                        )
                        
                        androidx.compose.animation.AnimatedVisibility(
                            visible = enteredWords.isNotEmpty(),
                            enter = androidx.compose.animation.fadeIn() + androidx.compose.animation.expandHorizontally(),
                            exit = androidx.compose.animation.fadeOut() + androidx.compose.animation.shrinkHorizontally()
                        ) {
                            TextButton(
                                onClick = { 
                                    repeat(enteredWords.size) { onRemoveWord(0) }
                                    verificationError = false
                                },
                                contentPadding = PaddingValues(horizontal = 8.dp, vertical = 0.dp),
                                modifier = Modifier.height(36.dp)
                            ) {
                                Text(
                                    text = stringResource(R.string.clear_all),
                                    style = MaterialTheme.typography.labelSmall,
                                    color = MaterialTheme.colorScheme.error,
                                    fontWeight = FontWeight.Bold
                                )
                            }
                        }
                    }

                    Surface(
                        modifier = Modifier
                            .fillMaxWidth()
                            .heightIn(min = 160.dp),
                        color = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f),
                        shape = RoundedCornerShape(24.dp),
                        border = BorderStroke(1.dp, borderColor)
                    ) {
                        androidx.compose.animation.AnimatedContent(
                            targetState = enteredWords.isEmpty(),
                            label = "words_container_content",
                            transitionSpec = {
                                androidx.compose.animation.fadeIn() togetherWith androidx.compose.animation.fadeOut()
                            }
                        ) { isEmpty ->
                            Box(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(16.dp)
                            ) {
                                if (isEmpty) {
                                    Text(
                                        text = stringResource(R.string.no_words_selected),
                                        style = MaterialTheme.typography.bodyMedium,
                                        color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.5f),
                                        modifier = Modifier.align(Alignment.Center)
                                    )
                                } else {
                                    FlowRow(
                                        modifier = Modifier.fillMaxWidth(),
                                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                                        verticalArrangement = Arrangement.spacedBy(8.dp)
                                    ) {
                                        enteredWords.forEachIndexed { index, word ->
                                            SimpleSelectedChip(
                                                word = word,
                                                index = index + 1,
                                                onRemove = { 
                                                    onRemoveWord(index)
                                                    verificationError = false
                                                }
                                            )
                                        }
                                    }
                                }
                            }
                        }
                    }

                    androidx.compose.animation.AnimatedVisibility(
                        visible = verificationError,
                        enter = androidx.compose.animation.expandVertically() + androidx.compose.animation.fadeIn(),
                        exit = androidx.compose.animation.shrinkVertically() + androidx.compose.animation.fadeOut()
                    ) {
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(top = 12.dp, start = 8.dp, end = 8.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.Center
                        ) {
                            Icon(
                                imageVector = Icons.Default.Error,
                                contentDescription = null,
                                tint = MaterialTheme.colorScheme.error,
                                modifier = Modifier.size(16.dp)
                            )
                            Spacer(modifier = Modifier.width(8.dp))
                            Text(
                                text = stringResource(R.string.wrong_order_error),
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.error,
                                fontWeight = FontWeight.SemiBold
                            )
                        }
                    }
                }
            }

            item {
                Column(modifier = Modifier.animateContentSize()) {
                    Text(
                        text = stringResource(R.string.available_words),
                        style = MaterialTheme.typography.titleSmall,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                    
                    Spacer(modifier = Modifier.height(12.dp))
                    
                    FlowRow(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(10.dp),
                        verticalArrangement = Arrangement.spacedBy(10.dp)
                    ) {
                        shuffledWords.forEach { word ->
                            val usageCount = enteredWords.count { it == word }
                            val totalCount = mnemonic.count { it == word }
                            val isUsed = usageCount >= totalCount
                            
                            SimpleWordChip(
                                word = word,
                                isEnabled = !isUsed,
                                onClick = { 
                                    onAddWord(word)
                                    verificationError = false
                                }
                            )
                        }
                    }
                }
            }
        }

        Surface(
            modifier = Modifier.fillMaxWidth(),
            tonalElevation = 8.dp,
            shadowElevation = 8.dp
        ) {
            Button(
                onClick = {
                    haptic.performHapticFeedback(HapticFeedbackType.LongPress)
                    if (enteredWords == mnemonic) {
                        verificationError = false
                        onVerify()
                    } else {
                        verificationError = true
                    }
                },
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp)
                    .height(56.dp),
                shape = RoundedCornerShape(16.dp),
                enabled = enteredWords.size == mnemonic.size
            ) {
                Text(
                    text = stringResource(R.string.verify_continue),
                    fontWeight = FontWeight.Bold,
                    style = MaterialTheme.typography.titleMedium
                )
            }
        }
    }
}

@Composable
fun WalletNameStep(
    walletName: String,
    onNameChange: (String) -> Unit,
    onCreate: () -> Unit
) {
    val haptic = LocalHapticFeedback.current
    Column(
        modifier = Modifier.fillMaxSize()
    ) {
        Column(
            modifier = Modifier
                .weight(1f)
                .padding(horizontal = 20.dp, vertical = 24.dp)
        ) {
            NexusTextField(
                value = walletName,
                onValueChange = onNameChange,
                label = stringResource(R.string.wallet_name_label),
                placeholder = stringResource(R.string.wallet_name_placeholder)
            )

            Spacer(modifier = Modifier.height(12.dp))

            Text(
                text = stringResource(R.string.wallet_name_tip),
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }

        Surface(
            modifier = Modifier.fillMaxWidth(),
            tonalElevation = 8.dp,
            shadowElevation = 8.dp
        ) {
            Button(
                onClick = {
                    haptic.performHapticFeedback(HapticFeedbackType.LongPress)
                    onCreate()
                },
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp)
                    .height(56.dp),
                shape = RoundedCornerShape(16.dp),
                enabled = walletName.isNotBlank()
            ) {
                Text(
                    text = stringResource(R.string.create_wallet),
                    fontWeight = FontWeight.Bold,
                    style = MaterialTheme.typography.titleMedium
                )
            }
        }
    }
}

@Composable
fun WalletSuccessStep(
    wallet: Wallet,
    onFinish: () -> Unit
) {
    val totalAssets = wallet.bitcoinCoins.size +
            wallet.solanaCoins.size +
            wallet.evmTokens.size +
            wallet.solanaCoins.flatMap { it.splTokens }.size

    Column(modifier = Modifier.fillMaxSize()) {
        Column(
            modifier = Modifier
                .weight(1f)
                .background(MaterialTheme.colorScheme.background)
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 20.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Spacer(modifier = Modifier.height(48.dp))

            Box(
                modifier = Modifier
                    .size(120.dp)
                    .clip(CircleShape)
                    .background(MaterialTheme.colorScheme.primaryContainer),
                contentAlignment = Alignment.Center
            ) {
                Icon(
                    imageVector = Icons.Default.CheckCircle,
                    contentDescription = "Success",
                    modifier = Modifier.size(64.dp),
                    tint = MaterialTheme.colorScheme.primary
                )
            }

            Spacer(modifier = Modifier.height(32.dp))

            Text(
                text = stringResource(R.string.wallet_created_success),
                style = MaterialTheme.typography.headlineMedium,
                fontWeight = FontWeight.Bold,
                textAlign = TextAlign.Center,
                color = MaterialTheme.colorScheme.onSurface
            )

            Spacer(modifier = Modifier.height(24.dp))

            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(24.dp),
                colors = CardDefaults.cardColors(
                    containerColor = MaterialTheme.colorScheme.surface
                ),
                border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant)
            ) {
                Column(
                    modifier = Modifier.padding(20.dp)
                ) {
                    Text(
                        text = stringResource(R.string.wallet_details),
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.onSurface
                    )

                    Spacer(modifier = Modifier.height(16.dp))

                    DetailRow(label = stringResource(R.string.name_label), value = wallet.name)
                    
                    Spacer(modifier = Modifier.height(16.dp))

                    Text(
                        stringResource(R.string.enabled_assets),
                        style = MaterialTheme.typography.labelMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        fontWeight = FontWeight.SemiBold
                    )

                    Spacer(modifier = Modifier.height(8.dp))

                    wallet.bitcoinCoins.forEach { coin ->
                        AssetDetailItem(
                            iconRes = R.drawable.bitcoin,
                            name = coin.name,
                            color = bitcoinLight,
                            isTestnet = coin.network.isTestnet
                        )
                    }

                    wallet.solanaCoins.forEach { coin ->
                        AssetDetailItem(
                            iconRes = R.drawable.solana,
                            name = coin.name,
                            color = solanaLight,
                            isTestnet = coin.network.isTestnet
                        )
                    }

                    wallet.evmTokens.forEach { token ->
                        val (color, iconRes) = when (token) {
                            is NativeETH -> Pair(ethereumLight, R.drawable.ethereum)
                            is USDCToken -> Pair(usdcLight, R.drawable.usdc)
                            is USDTToken -> Pair(usdtLight, R.drawable.tether)
                        }
                        AssetDetailItem(
                            iconRes = iconRes,
                            name = token.name,
                            color = color,
                            isTestnet = token.network.isTestnet
                        )
                    }

                    Spacer(modifier = Modifier.height(16.dp))
                    HorizontalDivider(color = MaterialTheme.colorScheme.outlineVariant)
                    Spacer(modifier = Modifier.height(16.dp))

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text(
                            text = stringResource(R.string.total_assets),
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                        Text(
                            text = totalAssets.toString(),
                            style = MaterialTheme.typography.titleLarge,
                            fontWeight = FontWeight.ExtraBold,
                            color = MaterialTheme.colorScheme.primary
                        )
                    }
                }
            }
            
            Spacer(modifier = Modifier.height(32.dp))
        }

        Surface(
            modifier = Modifier.fillMaxWidth(),
            tonalElevation = 8.dp,
            shadowElevation = 8.dp
        ) {
            Button(
                onClick = onFinish,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp)
                    .height(56.dp),
                shape = RoundedCornerShape(16.dp)
            ) {
                Icon(Icons.Outlined.Dashboard, contentDescription = null)
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    text = stringResource(R.string.go_to_dashboard),
                    fontWeight = FontWeight.Bold,
                    style = MaterialTheme.typography.titleMedium
                )
            }
        }
    }
}
